# Generated by Django 3.1.7 on 2021-03-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='درباره نویسنده'),
        ),
    ]
