# Generated by Django 3.2 on 2021-04-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210401_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, help_text='۳۰۰ کاراکتر', max_length=300, null=True, verbose_name='درباره نویسنده'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='عکس پروفایل با این ایمیل از Gravatar نشان داده میشود.', max_length=254, unique=True, verbose_name='آدرس ایمیل'),
        ),
    ]
