# Generated by Django 3.2 on 2021-04-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210407_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, help_text='آیا کاربر اجازه نوشتن مقاله جدید در سایت را دارد؟', verbose_name='کاربر نویسنده'),
        ),
    ]
