# Generated by Django 3.2 on 2021-04-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210403_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publish',), 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
